#!/bin/bash

# disable warnings about unused variables
# we source this file and export
# the variables in src/xettelkasten.
# Variable in '' will be used for
# env subsitution.
#
# shellcheck disable=SC2034
# shellcheck disable=SC2016

# template
ZETTEL_TEMPLATE="$ETC_DIR/templates/zettel.tex"

# structure
ZETTEL_FILENAME=zettel.tex
REFERENCE_FILENAME=references
TAG_FILENAME=tags

# directory stucture of a zettelkasten
# with the zettels foo and bar
#
# $ZETTEL_DATA
# ├── bar
# │   ├── $REFERENCE_FILENAME
# │   ├── $TAG_FILENAME
# │   └── $ZETTEL_FILENAME
# └── foo
#     ├── $REFERENCE_FILENAME
#     ├── $TAG_FILENAME
#     └── $ZETTEL_FILENAME

### User specific configuration defaults ###

ZETTEL_DATA="$HOME/.local/xettelkasten/my-zettel-kasten"
LOG_FILE="/tmp/xettelkasten_test.log"

# the above options will be overwritten
# if set in .config/xk/config

### for builtin userscripts ###
AUTHOR="$USER"

BIB_FILENAME="zettelkasten.bib"
BIB_PREAMBLE='@preamble{"\newcommand{\kasten}{$ZETTEL_DATA}"}'
BIB_ENTRY='
@zettel{$ZETTEL,
    title = {\href{\kasten/$ZETTEL/zettel.pdf}{$ESCAPED_ZETTEL}},
    author = {$AUTHOR},
}'
