#!/bin/bash

expand_template() (
    # populate subshell with vars
    NAME="${1//_/ }"
    export NAME
    export PREAMBLE="$PREAMBLE_FILE"
    envsubst < "$ZETTEL_TEMPLATE" || abort "Failed to expand template"
)

copy_files() {
    log "copy preamble"
    echo "copying..."
    
    # copy without copying permissions
    cp --no-preserve=mode -r "$ETC_DIR/templates/kasten/." "$ZETTEL_DATA" || abort "Failed to copy files"
}

zettel_init() {
    if [ -d "$ZETTEL_DATA" ]; then
        log "reinitializing"
        copy_files
        exit
    fi
    log "initializing new zettelkasten"
    mkdir "$ZETTEL_DATA" || abort "Failed to initialize zettelkasten"
    copy_files
}

zettel_ls() {
    list="$(find "$ZETTEL_DATA" -mindepth 2 -maxdepth 2 -type f -name "$ZETTEL_FILENAME")" || abort "Failed to list zettels"
    for z in $list
    do
        # use faster regex to emulate $(basename $(dirname ...))
        z_dir=${z%/*}
        z_final=${z_dir##*/}
        printf %"s\n" "$z_final"
    done
}

zettel_rm() {
    eval "$(parse_args "$@")"
    rm -r "$ZETTEL_DATA/${zettel:?}" || abort "Error removing zettel: $zettel"
}

zettel_path() {
    eval "$(parse_args "$@")"

    if [[ -n $zettel ]]; then
        [[ -d  "$ZETTEL_DATA/$zettel" ]] || abort "Zettel directory does not exist: $zettel"
        echo "$ZETTEL_DATA/$zettel"
        exit
    elif [[ -n $path ]]; then 
        supplied="$(dirname "$(dirname "$path")")"

        # test validity of path
        [[ "$ZETTEL_DATA" -ef "$supplied" ]] || abort "Invalid supplied path"
        [[ -f $path ]] || abort "Path does not exist: $path"
        
        basename "$(dirname "$path")"
        exit
    fi
    echo "$ZETTEL_DATA"
}

zettel_insert() {
    eval "$(parse_args "$@")"

    [[ -d "$ZETTEL_DATA/$zettel" ]] && abort "$zettel already exists, aborting"

    mkdir "$ZETTEL_DATA/$zettel" || abort "Failed to create zettel directory: $zettel"
    expand_template "$zettel" > "$ZETTEL_DATA/$zettel/$ZETTEL_FILENAME" || abort "Failed to create zettel file: $zettel"
    touch "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || abort "Failed to create reference file: $zettel"
    touch "$ZETTEL_DATA/$zettel/$TAG_FILENAME" || abort "Failed to create tag file: $zettel"
    log "created $zettel"
    echo "$zettel"
}

zettel_mv() {
    eval "$(parse_args "$@")"
    old_title=$zettel
    new_title=$new_zettel

    log "moving zettel"
    mv "$ZETTEL_DATA/$old_title" "$ZETTEL_DATA/$new_title" || abort "Failed to move zettel from $old_title to $new_title"

    log "updating references"
    for zet in $(zettel_ls); do
        # if removal of ref was successful, update it
        if ref_rm -z "$zet" -r "$old_title" &> /dev/null; then
            log "-- updating reference of $zet"
            ref_insert "-z" "$zet" "-r" "$new_title" || abort "Failed to update reference for $zet"
        fi
    done
    echo "$new_title"
}

# stop here if file is being sourced, not run
[[ "$0" != "$BASH_SOURCE" ]] && return

case "$1" in
    init)
        shift
        zettel_init
        ;;
    zet)
        ;&
    ls)
        shift
        zettel_ls
        ;;
    rm)
        shift
        zettel_rm "$@"
        ;;
    mv)
        shift
        zettel_mv "$@"
        ;;
    path)
        shift
        zettel_path "$@"
        ;;
    insert)
        shift
        zettel_insert "$@"
        ;;
    *)
        abort "Invalid top-level command: $1"
        ;;
esac
