#!/bin/bash

if ! command -v xettelkasten &> /dev/null
then
    echo "xettelkasten-core could not be found."
    echo "the asset generation depends on it."
    echo "please add src/xettelkasten to your path."
    exit 1
fi

# WORKDIR="$(cd "$(dirname "$0")" && pwd)"
# export  $(xargs -a "$WORKDIR/../config") # word splitting intetional

zettel="$(xettelkasten ls | rofi -i -async-pre-read 1 -dmenu)"

if [[ -z $zettel ]]; then
    exit
fi

path="$(xettelkasten path -z "$zettel")"

zathura "$path/zettel.pdf"
