#!/bin/bash

# all the installation script does
# is creating a symlink in .local/bin, as well as
# copying the default configuration to .config/xettelkasten/config

# symlink xk to entry script 
echo "linking src/xettelkasten to /usr/local/bin/xk"
ln -s "$(realpath ./src/xettelkasten)" "/usr/local/bin/xk"

# copy config
home="${XDG_CONFIG_HOME:-${HOME}/.config}"
echo "copying default config to $home/xk/config"
mkdir -p "$home/xk"
cp -n ./config.template "$home/xk/config" || echo config already present...
