#!/bin/bash

# all the installation script does
# is creating a symlink in .local/bin, as well as
# copying the default configuration to .config/xettelkasten/config

# symlink xk to entry script 
echo "linking src/xettelkasten to /usr/local/bin/xk"
ln -s "$(realpath ./src/xettelkasten)" "/usr/local/bin/xk"

# copy config
echo "copying default config to $XDG_CONFIG_HOME/xk/config"
mkdir -p "$XDG_CONFIG_HOME/xk"
cp -n ./config.template "$XDG_CONFIG_HOME/xk/config" || echo config already present...
