#!/bin/bash

set -e

git_check() {
    if [ -d "$ZETTEL_DATA/.git" ]; then
        log ".git directory exists"
        return 0
    else
        log ".git direcory does not exist."
        return 1
    fi
}

git_init() {
    log "cd into zettelkasten"
    cd "$ZETTEL_DATA" || exit 

    if git_check; then
       log "exists aborting"
       exit 0
    fi

    log "running git init"
    git init
}

git_cmd() {
    log "cd into zettelkasten"
    cd "$ZETTEL_DATA" || exit 

    log "running git" "$@"
    git "$@"
}

git_publish() {
   git_check || exit 0;
   git_cmd add -A
   timestamp=$(date -u +"%Y-%m-%d")
   git_cmd commit -m "publish $timestamp"
   git_cmd push
}

case "$1" in
    init)
        git_init
        ;;
    publish)
        git_publish
        ;;
    help)
        git_help
        ;;
    *)
        git_cmd "$@"
        ;;
esac
