#!/bin/bash

set -e
. "$ZETTEL_WORKDIR/common"

git_init() {
    log "cd into zettelkasten"
    cd $ZETTEL_DATA || exit 

    if [ -d .git ]; then
        info ".git direcory exists. Aborting"
        exit 0
    fi

    log "running git init"
    git init
}

git_cmd() {
    log "cd into zettelkasten"
    cd $ZETTEL_DATA || exit 

    if ! [ -d .git ]; then
        log ".git direcory does not exist. Aborting"
        info "run zettelkasten git init first."
        exit 0
    fi
    
    log "running git" "$@"
    echo "$(git "$@")"
}


git_help() {
    command_name=${0##*/}
    echo "
    $command_name
    Usage: $cli_name $command_name [command]
    Commands:
    init      initialize git repo in xettelkasten
    help      Help
    *         execute git command on xettelkasten 
    "
    exit 1
}

case "$1" in
    init)
        git_init
        ;;
    help)
        git_help
        ;;
    *)
        git_cmd "$@"
        ;;
esac
