#!/bin/bash

set -e
. "$ZETTEL_WORKDIR/common"

git_check() {
    if [ -d "$ZETTEL_DATA/.git" ]; then
        log ".git directory exists"
        return 0
    else
        log ".git direcory does not exist."
        return 1
    fi
}

git_init() {
    log "cd into zettelkasten"
    cd "$ZETTEL_DATA" || exit 

    if git_check; then
       info "exists aborting"
       exit 0
    fi

    log "running git init"
    # git init
}

git_cmd() {
    log "cd into zettelkasten"
    cd "$ZETTEL_DATA" || exit 

    
    log "running git" "$@"
    echo "$(git "$@")"
}

git_publish() {
   git_check || exit 0;
   tmux confirm -p "publish new zettel [y/N]" "display-message 'publishing...'" || exit 0
   git_cmd add -A
   timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
   git_cmd commit -m "publish $timestamp"
   git_cmd push
}

git_help() {
    command_name=${0##*/}
    echo "
    $command_name
    Usage: $cli_name $command_name [command]
    Commands:
    init      initialize git repo in xettelkasten
    help      Help
    *         execute git command on xettelkasten 
    "
    exit 1
}

case "$1" in
    init)
        git_init
        ;;
    publish)
        git_publish
        ;;
    help)
        git_help
        ;;
    *)
        git_cmd "$@"
        ;;
esac
