#!/bin/bash

set -e
. "$ZETTEL_WORKDIR/common"

nav_help() {
    command_name=${0##*/}
    echo "
    $command_name
    Usage: $cli_name $command_name [command]
    Commands:
    fzf       fuzzy find any zettel
    ref       select from references of current_zettel
    bref      select from back-references
              (zettel that reference the current)
    *         Help
    "
    exit 1
}

reference_file() {
    current_zettel=$1
    references="$ZETTEL_DATA/$current_zettel/${REFERENCE_FILENAME}"
    echo $references
}

fzf_navigate() {
    selected=$2
    zettel_session
    if [[ -z $selected ]]; then
        selected=$(cd $ZETTEL_DATA && ls | fzf-tmux )
        if [[ -z selected ]]; then
            tmux display-message "no zettel selected"
            exit 1
        fi
    fi
    open_zettel $selected
}

ref_navigate() {
    zettel_session
    references=$(reference_file $(viewing))
    selected=$( cat $references | fzf-tmux )
    open_zettel $selected
}

brefs() {
    target=$1
    # go through all zettels
    for zettel in $(zettel_list)
    do
        # check that the reference_file exists
        if ! [[ -f $(reference_file $zettel ) ]]; then
            continue
        fi
        # check that it is not empty
        references=$(cat $(reference_file $zettel ))
        if [[ -z $references ]]; then
            continue
        fi
        # go through the references
        for ref in $references
        do
            # check if current zettel is referenced
            if [[ $ref = $target ]]; then
                echo $zettel
            fi
        done
    done
}

bref_navigate() {
    zettel_session
    selected=$(brefs $(viewing) | fzf-tmux)
    open_zettel $selected
}

case "$1" in
    fzf)
        fzf_navigate $2
        ;;
    ref)
        ref_navigate
        ;;
    bref)
        bref_navigate
        ;;
    *)
        ref_help
        ;;
esac
