#!/bin/bash
set -e
. "$ZETTEL_WORKDIR/common"

ref_help() {
    command_name=${0##*/}
    echo "
    $command_name
    Usage: $cli_name $command_name [command]
    Commands:
    add      **add** new reference to current zettel
    rm       **remove** reference from current zettel
    *         Help
    "
    exit 1
}

ref_add() {
    zettel_session
    selected=$(zettel_list | fzf-tmux) || exit

    # if reference is already in references there is nothing todo
    if ! [[ -z "$(cat "$(reference_file "$(viewing)")" | grep -x "$selected")" ]]; then
        exit
    fi

    echo "$selected" >> "$(reference_file "$(viewing)")"
}

ref_rm() {
    zettel_session
    ref_file="$(reference_file "$(viewing)")"
    log "reference file:" "$ref_file"
    selected="$(cat "$ref_file" | fzf-tmux)" || exit
    log "selected: " "$selected"
	tmux confirm -p "remove reference \"$selected\" [y/N]" "display-message 'removed'" || exit
    log "confirmed"
	log "removing $selected from references"
    log "$(cat "$ref_file" | grep -v -x "$selected" > /tmp/zettelkasten_ref_cache)"
    log "updated references: " "$(cat /tmp/zettelkasten_ref_cache)"
    mv /tmp/zettelkasten_ref_cache "$ref_file"
}

case "$1" in
    add)
        ref_add
        ;;
    rm)
        ref_rm
        ;;
    *)
        ref_help
        ;;
esac
