#!/bin/bash
set -e
source "$ZETTEL_WORKDIR/utils"

ref_insert() {
    eval "$(parse_args "$@")"
    if grep -qx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" ; then
        log "reference already present"
        exit
    fi

    echo "$ref" >> "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME"
}

ref_ls() {
    eval "$(parse_args "$@")"
    grep -v ^$ "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || log "error during ref ls"
}

ref_rm() {
    eval "$(parse_args "$@")"

    if ! grep -qx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" ; then
        log "$ref not referenced by $zettel"
        return 1
    fi

    updated="$(grep -vx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME")" || updated=""
    echo "$updated" > "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME"
    return 0
}

# stop here if file is being sourced, not run
if [ "$0" != "$BASH_SOURCE" ] ; then
   return
fi

case "$1" in
    insert)
        shift
        ref_insert "$@"
        ;;
    ls)
        shift
        ref_ls "$@"
        ;;
    rm)
        shift
        ref_rm "$@"
        ;;
    *)
        echo "invalid ref command $1"
        ;;
esac
