#!/bin/bash
set -e
source "$ZETTEL_WORKDIR/utils"

parse_args() {
    OPTSTRING=":z:r:"

    while getopts ${OPTSTRING} opt; do
        case ${opt} in
            z)
                zettel=$OPTARG
                ;;
            r)
                ref=$OPTARG
                ;;
            :)
                echo "missing args"; exit
                ;;
            ?)
                echo "invalid option."; exit
                ;;
        esac
    done

    case "$zettel" in
        *\ * )
            info "name may not contain spaces"; exit
            ;;
    esac
    echo "zettel='$zettel'; ref='$ref'"
}

ref_insert() {
    shift && eval "$(parse_args "$@")"
    if grep -q "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" ; then
        log "reference already present"
        exit
    fi

    echo "$ref" >> "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME"
}

ref_ls() {
    shift && eval "$(parse_args "$@")"
    grep -v ^$ "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || log "error during ref ls"
}

ref_rm() {
    shift && eval "$(parse_args "$@")"

    if ! grep -q "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" ; then
        log "reference not present"
        exit
    fi

    updated="$(grep -vx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME")"
    echo "$updated" > "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME"
}

case "$1" in
    insert)
        ref_insert "$@"
        ;;
    ls)
        ref_ls "$@"
        ;;
    rm)
        ref_rm "$@"
        ;;
    *)
        echo "invalid ref command $1"
        ;;
esac
