#!/bin/bash

#
# this hook will gets called after a zettel is opened via go ... or zettel new
# in my case i use my window manager to close pdfs that were left open by
# previous zettels
#

if [ -z "$1" ]; then
    exit 0
fi

# TODO: adjust the pattern to make use of the filename
# filename=$1

pattern='..|select(.type?)|select(.type=="con" and .app_id != null)|select(.app_id|test("zathura"))|select(.name|test("/zettel.pdf"))|.pid'
pid="$(swaymsg -t get_tree | jq -r "$pattern")"

if [ -z "$pid" ]; then
    exit 0
fi

kill "$pid"
