#!/bin/bash

#
# this hook will gets called after a zettel is opened via go ... or zettel new
#

$NVIM_CMD --server "$NVIM_PIPE" --remote-send '<C-\><C-N>:VimtexView<CR>'
$NVIM_CMD --server "$NVIM_PIPE" --remote-send '<C-\><C-N>:VimtexCompileSS<CR>'


