#!/bin/bash
source .env

selected=$1
open_zettel= 
listening="/tmp/zettelkasten.pipe"

if [[ -z $selected ]]; then
    selected=$(cd $ZETTEL_KASTEN_HOME && ls | fzf-tmux)
fi

if [[ -z $selected ]]; then
    # do nothing
    exit 0
fi


# for some reason it outputs to sterr wtfffffff
nvim --server $listening --remote-expr "expand('%')" 2&>1 > /tmp/zettelkasten_open
current_zettel=$(</tmp/zettelkasten_open)
last=$(realpath $(dirname $current_zettel))

echo $selected >> $last/references

