#!/usr/bin/bash


tmux_running=$(pgrep tmux)
name="zettelkasten"

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $name
    exit 0
fi

if ! tmux has-session -t=$name 2> /dev/null; then
    tmux new-session -ds $name $HOME/git/tex_zettel/scripts/launch_editor
fi

tmux switch-client -t $name
