#!/bin/bash

if ! command -v xettelkasten &> /dev/null
then
    echo "xettelkasten-core could not be found."
    echo "the asset generation depends on it."
    echo "please add src/xettelkasten to your path."
    exit 1
fi

ASSET_WORKDIR="$(cd "$(dirname "$0")" && pwd)"
export ASSET_WORKDIR

export  $(xargs -a "$XDG_CONFIG_HOME/xettelkasten/config") # word splitting intetional

source "$ASSET_WORKDIR/healthcheck"

HEALTHY_NAMES=("${healthy[@]}")
HEALTHY_LIST=()
for healthy in "${HEALTHY_NAMES[@]}"; do
    path=$(xettelkasten path -z "$healthy")
    HEALTHY_LIST+=("$path")
done

export HEALTHY_LIST
export HEALTHY_NAMES

[[ $GEN_GLOSSARY -eq 1 ]] && source "$ASSET_WORKDIR/generators/glossary.sh" &>/dev/null
