#!/bin/bash
source .env

selected=$1
listening="/tmp/zettelkasten.pipe"

if [[ -z $selected ]]; then
    selected=$(cd $ZETTEL_KASTEN_HOME && ls | fzf-tmux)
fi

if [[ -z $selected ]]; then
    # do nothing
    exit 0
fi

# echo $selected > /tmp/zettel_last_opened
tmux rename-window -t 0 $selected
nvim --server $listening --remote "$ZETTEL_KASTEN_HOME/$selected/zettel.tex"


