#!/usr/bin/env bash
cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "== $script_name $timestamp $1"
}

zettel_session() {
    if ! tmux has-session -t="$SESSION_NAME" 2> /dev/null; then
        cmd="$NVIM_CMD --listen $NVIM_PIPE"
        tmux display-message "using command $cmd"
        tmux new-session \
            -c $ZETTEL_DATA \
            -ds $SESSION_NAME $cmd
    fi

    tmux switch-client -t $SESSION_NAME
}

viewing() {
    # for some reason it outputs to sterr wtf?
    nvim --server $NVIM_PIPE \
        --remote-expr "expand('%')" \
        2&>1 > /tmp/zettelkasten_open

    open=$(</tmp/zettelkasten_open)

    if [[ -z $open ]]
    then
        exit 1
    else
        echo $(cd $ZETTEL_DATA; realpath $(dirname $open))
    fi
}
