#!/bin/bash

# disable warnings about unused variables
# we source this file and export
# the variables in src/xettelkasten
# shellcheck disable=SC2034

# template
ZETTEL_TEMPLATE="$ZETTEL_WORKDIR/../resources/template.tex"

# the preamble relative to the zettel-kastens root (ZETTEL_DATA)
PREAMBLE_FILE="standalone_preamble.tex"

# structure
ZETTEL_FILENAME=zettel.tex
REFERENCE_FILENAME=references
TAG_FILENAME=tags

# directory stucture of a zettelkasten
# with the zettels foo and bar
#
# $ZETTEL_DATA
# ├── bar
# │   ├── $REFERENCE_FILENAME
# │   ├── $TAG_FILENAME
# │   └── $ZETTEL_FILENAME
# └── foo
#     ├── $REFERENCE_FILENAME
#     ├── $TAG_FILENAME
#     └── $ZETTEL_FILENAME

### User specific configuration defaults ###

ZETTEL_DATA="$HOME/.local/xettelkasten/my-zettel-kasten"
LOG_FILE="/tmp/xettelkasten_test.log"
ZETTEL_PREAMBLE="$HOME/git/preamble/preamble.tex"

# the above options will be overwritten
# if set in .config/xk/config
