#!/usr/bin/env bash

info() {
	tmux display-message -d 500 "$1" 
    log "info: $1"
}

editor_edit() {
    "$NVIM_CMD" --server "$NVIM_PIPE" --remote "$1"
}

viewing() {
    editor_current
}


nvim_cmd() {
    exit
}

nvim_expr() {
    if [[ -z $1 ]]; then
        log "empty expression: $1"
        exit
    fi
    "$NVIM_CMD" --server "$NVIM_PIPE" --remote-expr "$1"
}

editor_current() (
    nvim_expr "expand('%')" &> /tmp/zettelkasten_open
    open=$(</tmp/zettelkasten_open)

    if [[ -z $open ]]; then
        log "no open file found"
        exit
    fi
    cd "$ZETTEL_DATA" || exit
    current="$(basename "$(dirname "$open")")"
    log "editor file: $current"
    echo "$current"
)

zettel_session() {
    if ! tmux has-session -t="$SESSION_NAME" 2> /dev/null; then
		log "creating new session"

		log "removing old pipe"
		rm -rf "$NVIM_PIPE"

        cmd="$NVIM_CMD --listen $NVIM_PIPE"
		log "$cmd"

		log "$(tmux new-session -c "$ZETTEL_DATA" -d -s "$SESSION_NAME" "$cmd")"
        sleep 0.2
    fi

	log "tmux switch client"
    tmux switch-client -t "$SESSION_NAME"
}

user_input() {
    log "getting user input"
    nvim --server "$NVIM_PIPE" \
        --remote-expr "input('$1', '$2', 'file')" &> /tmp/zettelkasten_input

    open=$(</tmp/zettelkasten_input)
    log "result is $open"

    if [[ -z $open ]];
    then
        exit 1
    else
        echo "$open"
    fi
}
