#!/bin/bash

export NVIM_PIPE=/tmp/$NVIM_PIPE
export SESSION_NAME="--XeTtelkasten--"
export ZETTEL_TEMPLATE="$ZETTEL_WORKDIR/../template.tex"
export MAIN_TEMPLATE="$ZETTEL_WORKDIR/../main_template.tex"
export PREAMBLE_FILE="standalone_preamble.tex"
export ZETTEL_PREAMBLE="$ZETTEL_WORKDIR/../standalone_preamble.tex"

# structure
export ZETTEL_FILENAME=zettel.tex
export REFERENCE_FILENAME=references

# directory stucture of a zettelkasten
# with the zettels foo and bar
#
# $ZETTEL_DATA
# ├── bar
# │   ├── $REFERENCE_FILENAME
# │   └── $ZETTEL_FILENAME
# └── foo
#     ├── $REFERENCE_FILENAME
#     └── $ZETTEL_FILENAME
