#!/bin/bash
#
source "$ZETTEL_WORKDIR/globals"

log() {
	script_name=${0##*/}
	timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
	echo "== $script_name $timestamp" "$@" > "$LOG_FILE"
}

check_kasten() {
    if ! [[ -d $ZETTEL_DATA ]]; then
        info "$ZETTEL_DATA does not exist. Please run init"
        exit
    fi
    log "kasten directory: check passed"
}
