#!/usr/bin/env bash

set -e # exit on any non-0 exiting command

# this env var is used to reference scripts
# relative to the installation path of xk
export ZETTEL_WORKDIR
ZETTEL_WORKDIR="$(dirname "$(realpath "$0")")"

# source global options such as configuration etc
set -o allexport # export all variables after this
source "$ZETTEL_WORKDIR/default_config"
source "${XDG_CONFIG_HOME:-$HOME/.config}/xk/config"
source "$ZETTEL_WORKDIR/utils"
set +o allexport

CMD=$ZETTEL_WORKDIR/commands

case "$1" in
    ref)
        shift
        check_kasten
        "$CMD/ref" "$@"
        ;;
    tag)
        shift
        check_kasten
        "$CMD/tag" "$@"
        ;;
    git)
        shift
        check_kasten
        "$CMD/git" "$@"
        ;;
    *) # zettel
        [[ $2 == "init" ]] || check_kasten
        "$CMD/zettel" "$@"
        ;;
esac
