#!/usr/bin/env bash

set -e
export ZETTEL_WORKDIR=$(cd $(dirname $0) && pwd)
export $(cat "$ZETTEL_WORKDIR/config" | xargs)

export NVIM_PIPE="/tmp/$NVIM_PIPE"
. "$ZETTEL_WORKDIR/common"

cli_help() {
    cli_name=${0##*/}
    echo "
    $cli_name
    ZETTELKASTEN CLI
    Version: $(cat $ZETTEL_WORKDIR/VERSION)
    Usage: $cli_name [command]
    Commands:
    test      --testing--
    ref       change references
    goto      navigate zettel
    new       create new zettel
    status    get status
    *         Help
    "
    exit 1
}

CMD=$ZETTEL_WORKDIR/commands

case "$1" in
    tmux)
        export MODE="tmux"; shift
        ;;
    *)
        export MODE="cli"
        ;;
esac

case "$1" in
    ref)
        shift
        $CMD/ref $@ > $LOG_FILE
        ;;
    go)
        shift
        $CMD/go $@ > $LOG_FILE
        ;;
    new)
        $CMD/newzettel > $LOG_FILE
        ;;
    status)
        echo "currently viewing $(viewing)"
        ;;
    *)
        cli_help
        ;;
esac
