#!/usr/bin/env bash

set -e
export ZETTEL_WORKDIR=$(cd $(dirname $0) && pwd)
export $(cat "$ZETTEL_WORKDIR/../config" | xargs)

. $ZETTEL_WORKDIR/globals
. $ZETTEL_WORKDIR/common

cli_help() {
    cli_name=${0##*/}
    echo "
   XETTELKASTEN CLI
   ------------------------------------
    Version: $(cat $ZETTEL_WORKDIR/VERSION)
    Usage: $cli_name [command]

   Commands:
   ------------------------------------
    init      initialize xettelkasten
    ref       manage references
    go        navigate
    zettel    create/remove zettel
    status    output open zettel
    *         Help
    "
    exit 1
}

expand_main() {
    echo "$(
        export PREAMBLE=$PREAMBLE_FILE
        envsubst < $MAIN_TEMPLATE
    )"
}

init_kasten() {
    if [ -d "$ZETTEL_DATA" ]; then
        info "directory $ZETTEL_DATA already exists."
        echo "directory $ZETTEL_DATA already exists."

        info "updating preamble"
        rm -f "${ZETTEL_DATA:?}/${PREAMBLE_FILE:?}"
        cp  "$ZETTEL_PREAMBLE" "$ZETTEL_DATA/$PREAMBLE_FILE"

        info "updating mainfile"
        log "removing old glossary file"
        rm -f "${ZETTEL_DATA:?}/glossary.tex"
        log "creating new glossary file"
        echo "$(expand_main)" > "$ZETTEL_DATA/glossary.tex" 
        exit
    fi

    info "creating directory $ZETTEL_DATA"
    mkdir -p "$ZETTEL_DATA"

    info "symlinking preamble"
    cp  "$ZETTEL_PREAMBLE" "$ZETTEL_DATA/$PREAMBLE_FILE"
     
    info "creating glossary"
    echo "$(expand_main)" > "$ZETTEL_DATA/glossary.tex" 
}

CMD=$ZETTEL_WORKDIR/commands

case "$1" in
    init)
        init_kasten && exit
        ;;
    ref)
        check_kasten
        shift
        $CMD/ref $@
        ;;
    go)
        check_kasten
        shift
        $CMD/go $@
        ;;
    zettel)
        check_kasten
        shift
        $CMD/zettel $@
        ;;
    status)
        check_kasten
        echo "currently viewing $(viewing)"
        ;;
    *)
        cli_help
        ;;
esac
